title: MuscleMap Toolbox
description: MuscleMap documentation

# Use Just the Docs
remote_theme: just-the-docs/just-the-docs

# Project site settings
url: "https://musclemap.github.io"
baseurl: "/MuscleMap"

# Just the Docs options
search_enabled: true