title: "MuscleMap"
description: "Documentation for MuscleMap: an open-source toolbox for whole-body muscle and bone segmentation and quantitative analysis."

remote_theme: just-the-docs/just-the-docs

# Site URL (project page)
url: "https://musclemap.github.io"
baseurl: "/MuscleMap"

search_enabled: true

plugins:
  - jekyll-sitemap

# SEO default metadata
defaults:
  - scope:
      path: ""
    values:
      layout: default
      seo: true

# Optional but recommended:
just_the_docs:
  search:
    token_separator: /[\s\-/]+/
